// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: http.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "http.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* HttpMsg_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  HttpMsg_reflection_ = NULL;
const ::google::protobuf::Descriptor* HttpMsg_Header_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  HttpMsg_Header_reflection_ = NULL;
const ::google::protobuf::Descriptor* HttpMsg_Param_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  HttpMsg_Param_reflection_ = NULL;
const ::google::protobuf::Descriptor* HttpMsg_Upgrade_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  HttpMsg_Upgrade_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_http_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_http_2eproto() {
  protobuf_AddDesc_http_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "http.proto");
  GOOGLE_CHECK(file != NULL);
  HttpMsg_descriptor_ = file->message_type(0);
  static const int HttpMsg_offsets_[14] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HttpMsg, type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HttpMsg, http_major_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HttpMsg, http_minor_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HttpMsg, content_length_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HttpMsg, method_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HttpMsg, status_code_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HttpMsg, encoding_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HttpMsg, url_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HttpMsg, headers_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HttpMsg, body_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HttpMsg, params_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HttpMsg, upgrade_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HttpMsg, path_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HttpMsg, is_decoding_),
  };
  HttpMsg_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      HttpMsg_descriptor_,
      HttpMsg::default_instance_,
      HttpMsg_offsets_,
      -1,
      -1,
      -1,
      sizeof(HttpMsg),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HttpMsg, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HttpMsg, _is_default_instance_));
  HttpMsg_Header_descriptor_ = HttpMsg_descriptor_->nested_type(0);
  static const int HttpMsg_Header_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HttpMsg_Header, header_name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HttpMsg_Header, header_value_),
  };
  HttpMsg_Header_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      HttpMsg_Header_descriptor_,
      HttpMsg_Header::default_instance_,
      HttpMsg_Header_offsets_,
      -1,
      -1,
      -1,
      sizeof(HttpMsg_Header),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HttpMsg_Header, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HttpMsg_Header, _is_default_instance_));
  HttpMsg_Param_descriptor_ = HttpMsg_descriptor_->nested_type(1);
  static const int HttpMsg_Param_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HttpMsg_Param, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HttpMsg_Param, value_),
  };
  HttpMsg_Param_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      HttpMsg_Param_descriptor_,
      HttpMsg_Param::default_instance_,
      HttpMsg_Param_offsets_,
      -1,
      -1,
      -1,
      sizeof(HttpMsg_Param),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HttpMsg_Param, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HttpMsg_Param, _is_default_instance_));
  HttpMsg_Upgrade_descriptor_ = HttpMsg_descriptor_->nested_type(2);
  static const int HttpMsg_Upgrade_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HttpMsg_Upgrade, is_upgrade_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HttpMsg_Upgrade, protocol_),
  };
  HttpMsg_Upgrade_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      HttpMsg_Upgrade_descriptor_,
      HttpMsg_Upgrade::default_instance_,
      HttpMsg_Upgrade_offsets_,
      -1,
      -1,
      -1,
      sizeof(HttpMsg_Upgrade),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HttpMsg_Upgrade, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HttpMsg_Upgrade, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_http_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      HttpMsg_descriptor_, &HttpMsg::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      HttpMsg_Header_descriptor_, &HttpMsg_Header::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      HttpMsg_Param_descriptor_, &HttpMsg_Param::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      HttpMsg_Upgrade_descriptor_, &HttpMsg_Upgrade::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_http_2eproto() {
  delete HttpMsg::default_instance_;
  delete HttpMsg_reflection_;
  delete HttpMsg_Header::default_instance_;
  delete HttpMsg_Header_reflection_;
  delete HttpMsg_Param::default_instance_;
  delete HttpMsg_Param_reflection_;
  delete HttpMsg_Upgrade::default_instance_;
  delete HttpMsg_Upgrade_reflection_;
}

void protobuf_AddDesc_http_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_http_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\nhttp.proto\"\275\003\n\007HttpMsg\022\014\n\004type\030\001 \001(\005\022\022"
    "\n\nhttp_major\030\002 \001(\005\022\022\n\nhttp_minor\030\003 \001(\005\022\026"
    "\n\016content_length\030\004 \001(\005\022\016\n\006method\030\005 \001(\005\022\023"
    "\n\013status_code\030\006 \001(\005\022\020\n\010encoding\030\007 \001(\005\022\013\n"
    "\003url\030\010 \001(\t\022 \n\007headers\030\t \003(\0132\017.HttpMsg.He"
    "ader\022\014\n\004body\030\n \001(\014\022\036\n\006params\030\013 \003(\0132\016.Htt"
    "pMsg.Param\022!\n\007upgrade\030\014 \001(\0132\020.HttpMsg.Up"
    "grade\022\014\n\004path\030\016 \001(\t\022\023\n\013is_decoding\030\017 \001(\010"
    "\0323\n\006Header\022\023\n\013header_name\030\001 \001(\t\022\024\n\014heade"
    "r_value\030\002 \001(\014\032$\n\005Param\022\014\n\004name\030\001 \001(\t\022\r\n\005"
    "value\030\002 \001(\t\032/\n\007Upgrade\022\022\n\nis_upgrade\030\001 \001"
    "(\010\022\020\n\010protocol\030\002 \001(\tb\006proto3", 468);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "http.proto", &protobuf_RegisterTypes);
  HttpMsg::default_instance_ = new HttpMsg();
  HttpMsg_Header::default_instance_ = new HttpMsg_Header();
  HttpMsg_Param::default_instance_ = new HttpMsg_Param();
  HttpMsg_Upgrade::default_instance_ = new HttpMsg_Upgrade();
  HttpMsg::default_instance_->InitAsDefaultInstance();
  HttpMsg_Header::default_instance_->InitAsDefaultInstance();
  HttpMsg_Param::default_instance_->InitAsDefaultInstance();
  HttpMsg_Upgrade::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_http_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_http_2eproto {
  StaticDescriptorInitializer_http_2eproto() {
    protobuf_AddDesc_http_2eproto();
  }
} static_descriptor_initializer_http_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int HttpMsg_Header::kHeaderNameFieldNumber;
const int HttpMsg_Header::kHeaderValueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

HttpMsg_Header::HttpMsg_Header()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:HttpMsg.Header)
}

void HttpMsg_Header::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

HttpMsg_Header::HttpMsg_Header(const HttpMsg_Header& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:HttpMsg.Header)
}

void HttpMsg_Header::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  header_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  header_value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

HttpMsg_Header::~HttpMsg_Header() {
  // @@protoc_insertion_point(destructor:HttpMsg.Header)
  SharedDtor();
}

void HttpMsg_Header::SharedDtor() {
  header_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  header_value_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void HttpMsg_Header::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* HttpMsg_Header::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return HttpMsg_Header_descriptor_;
}

const HttpMsg_Header& HttpMsg_Header::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_http_2eproto();
  return *default_instance_;
}

HttpMsg_Header* HttpMsg_Header::default_instance_ = NULL;

HttpMsg_Header* HttpMsg_Header::New(::google::protobuf::Arena* arena) const {
  HttpMsg_Header* n = new HttpMsg_Header;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void HttpMsg_Header::Clear() {
// @@protoc_insertion_point(message_clear_start:HttpMsg.Header)
  header_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  header_value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool HttpMsg_Header::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:HttpMsg.Header)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string header_name = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_header_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->header_name().data(), this->header_name().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "HttpMsg.Header.header_name"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_header_value;
        break;
      }

      // optional bytes header_value = 2;
      case 2: {
        if (tag == 18) {
         parse_header_value:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_header_value()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:HttpMsg.Header)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:HttpMsg.Header)
  return false;
#undef DO_
}

void HttpMsg_Header::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:HttpMsg.Header)
  // optional string header_name = 1;
  if (this->header_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->header_name().data(), this->header_name().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "HttpMsg.Header.header_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->header_name(), output);
  }

  // optional bytes header_value = 2;
  if (this->header_value().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      2, this->header_value(), output);
  }

  // @@protoc_insertion_point(serialize_end:HttpMsg.Header)
}

::google::protobuf::uint8* HttpMsg_Header::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:HttpMsg.Header)
  // optional string header_name = 1;
  if (this->header_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->header_name().data(), this->header_name().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "HttpMsg.Header.header_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->header_name(), target);
  }

  // optional bytes header_value = 2;
  if (this->header_value().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        2, this->header_value(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:HttpMsg.Header)
  return target;
}

int HttpMsg_Header::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:HttpMsg.Header)
  int total_size = 0;

  // optional string header_name = 1;
  if (this->header_name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->header_name());
  }

  // optional bytes header_value = 2;
  if (this->header_value().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->header_value());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void HttpMsg_Header::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:HttpMsg.Header)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const HttpMsg_Header* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const HttpMsg_Header>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:HttpMsg.Header)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:HttpMsg.Header)
    MergeFrom(*source);
  }
}

void HttpMsg_Header::MergeFrom(const HttpMsg_Header& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:HttpMsg.Header)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.header_name().size() > 0) {

    header_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.header_name_);
  }
  if (from.header_value().size() > 0) {

    header_value_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.header_value_);
  }
}

void HttpMsg_Header::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:HttpMsg.Header)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void HttpMsg_Header::CopyFrom(const HttpMsg_Header& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:HttpMsg.Header)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool HttpMsg_Header::IsInitialized() const {

  return true;
}

void HttpMsg_Header::Swap(HttpMsg_Header* other) {
  if (other == this) return;
  InternalSwap(other);
}
void HttpMsg_Header::InternalSwap(HttpMsg_Header* other) {
  header_name_.Swap(&other->header_name_);
  header_value_.Swap(&other->header_value_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata HttpMsg_Header::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = HttpMsg_Header_descriptor_;
  metadata.reflection = HttpMsg_Header_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int HttpMsg_Param::kNameFieldNumber;
const int HttpMsg_Param::kValueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

HttpMsg_Param::HttpMsg_Param()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:HttpMsg.Param)
}

void HttpMsg_Param::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

HttpMsg_Param::HttpMsg_Param(const HttpMsg_Param& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:HttpMsg.Param)
}

void HttpMsg_Param::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

HttpMsg_Param::~HttpMsg_Param() {
  // @@protoc_insertion_point(destructor:HttpMsg.Param)
  SharedDtor();
}

void HttpMsg_Param::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  value_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void HttpMsg_Param::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* HttpMsg_Param::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return HttpMsg_Param_descriptor_;
}

const HttpMsg_Param& HttpMsg_Param::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_http_2eproto();
  return *default_instance_;
}

HttpMsg_Param* HttpMsg_Param::default_instance_ = NULL;

HttpMsg_Param* HttpMsg_Param::New(::google::protobuf::Arena* arena) const {
  HttpMsg_Param* n = new HttpMsg_Param;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void HttpMsg_Param::Clear() {
// @@protoc_insertion_point(message_clear_start:HttpMsg.Param)
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool HttpMsg_Param::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:HttpMsg.Param)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string name = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "HttpMsg.Param.name"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_value;
        break;
      }

      // optional string value = 2;
      case 2: {
        if (tag == 18) {
         parse_value:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_value()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->value().data(), this->value().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "HttpMsg.Param.value"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:HttpMsg.Param)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:HttpMsg.Param)
  return false;
#undef DO_
}

void HttpMsg_Param::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:HttpMsg.Param)
  // optional string name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "HttpMsg.Param.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // optional string value = 2;
  if (this->value().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->value().data(), this->value().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "HttpMsg.Param.value");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->value(), output);
  }

  // @@protoc_insertion_point(serialize_end:HttpMsg.Param)
}

::google::protobuf::uint8* HttpMsg_Param::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:HttpMsg.Param)
  // optional string name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "HttpMsg.Param.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // optional string value = 2;
  if (this->value().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->value().data(), this->value().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "HttpMsg.Param.value");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->value(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:HttpMsg.Param)
  return target;
}

int HttpMsg_Param::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:HttpMsg.Param)
  int total_size = 0;

  // optional string name = 1;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  // optional string value = 2;
  if (this->value().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->value());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void HttpMsg_Param::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:HttpMsg.Param)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const HttpMsg_Param* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const HttpMsg_Param>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:HttpMsg.Param)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:HttpMsg.Param)
    MergeFrom(*source);
  }
}

void HttpMsg_Param::MergeFrom(const HttpMsg_Param& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:HttpMsg.Param)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from.value().size() > 0) {

    value_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.value_);
  }
}

void HttpMsg_Param::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:HttpMsg.Param)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void HttpMsg_Param::CopyFrom(const HttpMsg_Param& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:HttpMsg.Param)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool HttpMsg_Param::IsInitialized() const {

  return true;
}

void HttpMsg_Param::Swap(HttpMsg_Param* other) {
  if (other == this) return;
  InternalSwap(other);
}
void HttpMsg_Param::InternalSwap(HttpMsg_Param* other) {
  name_.Swap(&other->name_);
  value_.Swap(&other->value_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata HttpMsg_Param::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = HttpMsg_Param_descriptor_;
  metadata.reflection = HttpMsg_Param_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int HttpMsg_Upgrade::kIsUpgradeFieldNumber;
const int HttpMsg_Upgrade::kProtocolFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

HttpMsg_Upgrade::HttpMsg_Upgrade()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:HttpMsg.Upgrade)
}

void HttpMsg_Upgrade::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

HttpMsg_Upgrade::HttpMsg_Upgrade(const HttpMsg_Upgrade& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:HttpMsg.Upgrade)
}

void HttpMsg_Upgrade::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  is_upgrade_ = false;
  protocol_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

HttpMsg_Upgrade::~HttpMsg_Upgrade() {
  // @@protoc_insertion_point(destructor:HttpMsg.Upgrade)
  SharedDtor();
}

void HttpMsg_Upgrade::SharedDtor() {
  protocol_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void HttpMsg_Upgrade::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* HttpMsg_Upgrade::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return HttpMsg_Upgrade_descriptor_;
}

const HttpMsg_Upgrade& HttpMsg_Upgrade::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_http_2eproto();
  return *default_instance_;
}

HttpMsg_Upgrade* HttpMsg_Upgrade::default_instance_ = NULL;

HttpMsg_Upgrade* HttpMsg_Upgrade::New(::google::protobuf::Arena* arena) const {
  HttpMsg_Upgrade* n = new HttpMsg_Upgrade;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void HttpMsg_Upgrade::Clear() {
// @@protoc_insertion_point(message_clear_start:HttpMsg.Upgrade)
  is_upgrade_ = false;
  protocol_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool HttpMsg_Upgrade::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:HttpMsg.Upgrade)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional bool is_upgrade = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &is_upgrade_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_protocol;
        break;
      }

      // optional string protocol = 2;
      case 2: {
        if (tag == 18) {
         parse_protocol:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_protocol()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->protocol().data(), this->protocol().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "HttpMsg.Upgrade.protocol"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:HttpMsg.Upgrade)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:HttpMsg.Upgrade)
  return false;
#undef DO_
}

void HttpMsg_Upgrade::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:HttpMsg.Upgrade)
  // optional bool is_upgrade = 1;
  if (this->is_upgrade() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->is_upgrade(), output);
  }

  // optional string protocol = 2;
  if (this->protocol().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->protocol().data(), this->protocol().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "HttpMsg.Upgrade.protocol");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->protocol(), output);
  }

  // @@protoc_insertion_point(serialize_end:HttpMsg.Upgrade)
}

::google::protobuf::uint8* HttpMsg_Upgrade::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:HttpMsg.Upgrade)
  // optional bool is_upgrade = 1;
  if (this->is_upgrade() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->is_upgrade(), target);
  }

  // optional string protocol = 2;
  if (this->protocol().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->protocol().data(), this->protocol().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "HttpMsg.Upgrade.protocol");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->protocol(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:HttpMsg.Upgrade)
  return target;
}

int HttpMsg_Upgrade::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:HttpMsg.Upgrade)
  int total_size = 0;

  // optional bool is_upgrade = 1;
  if (this->is_upgrade() != 0) {
    total_size += 1 + 1;
  }

  // optional string protocol = 2;
  if (this->protocol().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->protocol());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void HttpMsg_Upgrade::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:HttpMsg.Upgrade)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const HttpMsg_Upgrade* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const HttpMsg_Upgrade>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:HttpMsg.Upgrade)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:HttpMsg.Upgrade)
    MergeFrom(*source);
  }
}

void HttpMsg_Upgrade::MergeFrom(const HttpMsg_Upgrade& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:HttpMsg.Upgrade)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.is_upgrade() != 0) {
    set_is_upgrade(from.is_upgrade());
  }
  if (from.protocol().size() > 0) {

    protocol_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.protocol_);
  }
}

void HttpMsg_Upgrade::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:HttpMsg.Upgrade)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void HttpMsg_Upgrade::CopyFrom(const HttpMsg_Upgrade& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:HttpMsg.Upgrade)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool HttpMsg_Upgrade::IsInitialized() const {

  return true;
}

void HttpMsg_Upgrade::Swap(HttpMsg_Upgrade* other) {
  if (other == this) return;
  InternalSwap(other);
}
void HttpMsg_Upgrade::InternalSwap(HttpMsg_Upgrade* other) {
  std::swap(is_upgrade_, other->is_upgrade_);
  protocol_.Swap(&other->protocol_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata HttpMsg_Upgrade::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = HttpMsg_Upgrade_descriptor_;
  metadata.reflection = HttpMsg_Upgrade_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int HttpMsg::kTypeFieldNumber;
const int HttpMsg::kHttpMajorFieldNumber;
const int HttpMsg::kHttpMinorFieldNumber;
const int HttpMsg::kContentLengthFieldNumber;
const int HttpMsg::kMethodFieldNumber;
const int HttpMsg::kStatusCodeFieldNumber;
const int HttpMsg::kEncodingFieldNumber;
const int HttpMsg::kUrlFieldNumber;
const int HttpMsg::kHeadersFieldNumber;
const int HttpMsg::kBodyFieldNumber;
const int HttpMsg::kParamsFieldNumber;
const int HttpMsg::kUpgradeFieldNumber;
const int HttpMsg::kPathFieldNumber;
const int HttpMsg::kIsDecodingFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

HttpMsg::HttpMsg()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:HttpMsg)
}

void HttpMsg::InitAsDefaultInstance() {
  _is_default_instance_ = true;
  upgrade_ = const_cast< ::HttpMsg_Upgrade*>(&::HttpMsg_Upgrade::default_instance());
}

HttpMsg::HttpMsg(const HttpMsg& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:HttpMsg)
}

void HttpMsg::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  type_ = 0;
  http_major_ = 0;
  http_minor_ = 0;
  content_length_ = 0;
  method_ = 0;
  status_code_ = 0;
  encoding_ = 0;
  url_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  body_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  upgrade_ = NULL;
  path_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  is_decoding_ = false;
}

HttpMsg::~HttpMsg() {
  // @@protoc_insertion_point(destructor:HttpMsg)
  SharedDtor();
}

void HttpMsg::SharedDtor() {
  url_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  body_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  path_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
    delete upgrade_;
  }
}

void HttpMsg::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* HttpMsg::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return HttpMsg_descriptor_;
}

const HttpMsg& HttpMsg::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_http_2eproto();
  return *default_instance_;
}

HttpMsg* HttpMsg::default_instance_ = NULL;

HttpMsg* HttpMsg::New(::google::protobuf::Arena* arena) const {
  HttpMsg* n = new HttpMsg;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void HttpMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:HttpMsg)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(HttpMsg, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<HttpMsg*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(type_, status_code_);
  encoding_ = 0;
  url_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  body_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (GetArenaNoVirtual() == NULL && upgrade_ != NULL) delete upgrade_;
  upgrade_ = NULL;
  path_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  is_decoding_ = false;

#undef ZR_HELPER_
#undef ZR_

  headers_.Clear();
  params_.Clear();
}

bool HttpMsg::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:HttpMsg)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 type = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &type_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_http_major;
        break;
      }

      // optional int32 http_major = 2;
      case 2: {
        if (tag == 16) {
         parse_http_major:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &http_major_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_http_minor;
        break;
      }

      // optional int32 http_minor = 3;
      case 3: {
        if (tag == 24) {
         parse_http_minor:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &http_minor_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_content_length;
        break;
      }

      // optional int32 content_length = 4;
      case 4: {
        if (tag == 32) {
         parse_content_length:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &content_length_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_method;
        break;
      }

      // optional int32 method = 5;
      case 5: {
        if (tag == 40) {
         parse_method:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &method_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(48)) goto parse_status_code;
        break;
      }

      // optional int32 status_code = 6;
      case 6: {
        if (tag == 48) {
         parse_status_code:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &status_code_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(56)) goto parse_encoding;
        break;
      }

      // optional int32 encoding = 7;
      case 7: {
        if (tag == 56) {
         parse_encoding:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &encoding_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(66)) goto parse_url;
        break;
      }

      // optional string url = 8;
      case 8: {
        if (tag == 66) {
         parse_url:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_url()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->url().data(), this->url().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "HttpMsg.url"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(74)) goto parse_headers;
        break;
      }

      // repeated .HttpMsg.Header headers = 9;
      case 9: {
        if (tag == 74) {
         parse_headers:
          DO_(input->IncrementRecursionDepth());
         parse_loop_headers:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_headers()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(74)) goto parse_loop_headers;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectTag(82)) goto parse_body;
        break;
      }

      // optional bytes body = 10;
      case 10: {
        if (tag == 82) {
         parse_body:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_body()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(90)) goto parse_params;
        break;
      }

      // repeated .HttpMsg.Param params = 11;
      case 11: {
        if (tag == 90) {
         parse_params:
          DO_(input->IncrementRecursionDepth());
         parse_loop_params:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_params()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(90)) goto parse_loop_params;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectTag(98)) goto parse_upgrade;
        break;
      }

      // optional .HttpMsg.Upgrade upgrade = 12;
      case 12: {
        if (tag == 98) {
         parse_upgrade:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_upgrade()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(114)) goto parse_path;
        break;
      }

      // optional string path = 14;
      case 14: {
        if (tag == 114) {
         parse_path:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_path()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->path().data(), this->path().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "HttpMsg.path"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(120)) goto parse_is_decoding;
        break;
      }

      // optional bool is_decoding = 15;
      case 15: {
        if (tag == 120) {
         parse_is_decoding:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &is_decoding_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:HttpMsg)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:HttpMsg)
  return false;
#undef DO_
}

void HttpMsg::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:HttpMsg)
  // optional int32 type = 1;
  if (this->type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->type(), output);
  }

  // optional int32 http_major = 2;
  if (this->http_major() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->http_major(), output);
  }

  // optional int32 http_minor = 3;
  if (this->http_minor() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->http_minor(), output);
  }

  // optional int32 content_length = 4;
  if (this->content_length() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->content_length(), output);
  }

  // optional int32 method = 5;
  if (this->method() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->method(), output);
  }

  // optional int32 status_code = 6;
  if (this->status_code() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(6, this->status_code(), output);
  }

  // optional int32 encoding = 7;
  if (this->encoding() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(7, this->encoding(), output);
  }

  // optional string url = 8;
  if (this->url().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->url().data(), this->url().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "HttpMsg.url");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      8, this->url(), output);
  }

  // repeated .HttpMsg.Header headers = 9;
  for (unsigned int i = 0, n = this->headers_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      9, this->headers(i), output);
  }

  // optional bytes body = 10;
  if (this->body().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      10, this->body(), output);
  }

  // repeated .HttpMsg.Param params = 11;
  for (unsigned int i = 0, n = this->params_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      11, this->params(i), output);
  }

  // optional .HttpMsg.Upgrade upgrade = 12;
  if (this->has_upgrade()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      12, *this->upgrade_, output);
  }

  // optional string path = 14;
  if (this->path().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->path().data(), this->path().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "HttpMsg.path");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      14, this->path(), output);
  }

  // optional bool is_decoding = 15;
  if (this->is_decoding() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(15, this->is_decoding(), output);
  }

  // @@protoc_insertion_point(serialize_end:HttpMsg)
}

::google::protobuf::uint8* HttpMsg::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:HttpMsg)
  // optional int32 type = 1;
  if (this->type() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->type(), target);
  }

  // optional int32 http_major = 2;
  if (this->http_major() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->http_major(), target);
  }

  // optional int32 http_minor = 3;
  if (this->http_minor() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->http_minor(), target);
  }

  // optional int32 content_length = 4;
  if (this->content_length() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->content_length(), target);
  }

  // optional int32 method = 5;
  if (this->method() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->method(), target);
  }

  // optional int32 status_code = 6;
  if (this->status_code() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(6, this->status_code(), target);
  }

  // optional int32 encoding = 7;
  if (this->encoding() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(7, this->encoding(), target);
  }

  // optional string url = 8;
  if (this->url().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->url().data(), this->url().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "HttpMsg.url");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        8, this->url(), target);
  }

  // repeated .HttpMsg.Header headers = 9;
  for (unsigned int i = 0, n = this->headers_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        9, this->headers(i), false, target);
  }

  // optional bytes body = 10;
  if (this->body().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        10, this->body(), target);
  }

  // repeated .HttpMsg.Param params = 11;
  for (unsigned int i = 0, n = this->params_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        11, this->params(i), false, target);
  }

  // optional .HttpMsg.Upgrade upgrade = 12;
  if (this->has_upgrade()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        12, *this->upgrade_, false, target);
  }

  // optional string path = 14;
  if (this->path().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->path().data(), this->path().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "HttpMsg.path");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        14, this->path(), target);
  }

  // optional bool is_decoding = 15;
  if (this->is_decoding() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(15, this->is_decoding(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:HttpMsg)
  return target;
}

int HttpMsg::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:HttpMsg)
  int total_size = 0;

  // optional int32 type = 1;
  if (this->type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->type());
  }

  // optional int32 http_major = 2;
  if (this->http_major() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->http_major());
  }

  // optional int32 http_minor = 3;
  if (this->http_minor() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->http_minor());
  }

  // optional int32 content_length = 4;
  if (this->content_length() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->content_length());
  }

  // optional int32 method = 5;
  if (this->method() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->method());
  }

  // optional int32 status_code = 6;
  if (this->status_code() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->status_code());
  }

  // optional int32 encoding = 7;
  if (this->encoding() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->encoding());
  }

  // optional string url = 8;
  if (this->url().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->url());
  }

  // optional bytes body = 10;
  if (this->body().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->body());
  }

  // optional .HttpMsg.Upgrade upgrade = 12;
  if (this->has_upgrade()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->upgrade_);
  }

  // optional string path = 14;
  if (this->path().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->path());
  }

  // optional bool is_decoding = 15;
  if (this->is_decoding() != 0) {
    total_size += 1 + 1;
  }

  // repeated .HttpMsg.Header headers = 9;
  total_size += 1 * this->headers_size();
  for (int i = 0; i < this->headers_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->headers(i));
  }

  // repeated .HttpMsg.Param params = 11;
  total_size += 1 * this->params_size();
  for (int i = 0; i < this->params_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->params(i));
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void HttpMsg::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:HttpMsg)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const HttpMsg* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const HttpMsg>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:HttpMsg)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:HttpMsg)
    MergeFrom(*source);
  }
}

void HttpMsg::MergeFrom(const HttpMsg& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:HttpMsg)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  headers_.MergeFrom(from.headers_);
  params_.MergeFrom(from.params_);
  if (from.type() != 0) {
    set_type(from.type());
  }
  if (from.http_major() != 0) {
    set_http_major(from.http_major());
  }
  if (from.http_minor() != 0) {
    set_http_minor(from.http_minor());
  }
  if (from.content_length() != 0) {
    set_content_length(from.content_length());
  }
  if (from.method() != 0) {
    set_method(from.method());
  }
  if (from.status_code() != 0) {
    set_status_code(from.status_code());
  }
  if (from.encoding() != 0) {
    set_encoding(from.encoding());
  }
  if (from.url().size() > 0) {

    url_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.url_);
  }
  if (from.body().size() > 0) {

    body_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.body_);
  }
  if (from.has_upgrade()) {
    mutable_upgrade()->::HttpMsg_Upgrade::MergeFrom(from.upgrade());
  }
  if (from.path().size() > 0) {

    path_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.path_);
  }
  if (from.is_decoding() != 0) {
    set_is_decoding(from.is_decoding());
  }
}

void HttpMsg::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:HttpMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void HttpMsg::CopyFrom(const HttpMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:HttpMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool HttpMsg::IsInitialized() const {

  return true;
}

void HttpMsg::Swap(HttpMsg* other) {
  if (other == this) return;
  InternalSwap(other);
}
void HttpMsg::InternalSwap(HttpMsg* other) {
  std::swap(type_, other->type_);
  std::swap(http_major_, other->http_major_);
  std::swap(http_minor_, other->http_minor_);
  std::swap(content_length_, other->content_length_);
  std::swap(method_, other->method_);
  std::swap(status_code_, other->status_code_);
  std::swap(encoding_, other->encoding_);
  url_.Swap(&other->url_);
  headers_.UnsafeArenaSwap(&other->headers_);
  body_.Swap(&other->body_);
  params_.UnsafeArenaSwap(&other->params_);
  std::swap(upgrade_, other->upgrade_);
  path_.Swap(&other->path_);
  std::swap(is_decoding_, other->is_decoding_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata HttpMsg::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = HttpMsg_descriptor_;
  metadata.reflection = HttpMsg_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// HttpMsg_Header

// optional string header_name = 1;
void HttpMsg_Header::clear_header_name() {
  header_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& HttpMsg_Header::header_name() const {
  // @@protoc_insertion_point(field_get:HttpMsg.Header.header_name)
  return header_name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void HttpMsg_Header::set_header_name(const ::std::string& value) {
  
  header_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:HttpMsg.Header.header_name)
}
 void HttpMsg_Header::set_header_name(const char* value) {
  
  header_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:HttpMsg.Header.header_name)
}
 void HttpMsg_Header::set_header_name(const char* value, size_t size) {
  
  header_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:HttpMsg.Header.header_name)
}
 ::std::string* HttpMsg_Header::mutable_header_name() {
  
  // @@protoc_insertion_point(field_mutable:HttpMsg.Header.header_name)
  return header_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* HttpMsg_Header::release_header_name() {
  // @@protoc_insertion_point(field_release:HttpMsg.Header.header_name)
  
  return header_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void HttpMsg_Header::set_allocated_header_name(::std::string* header_name) {
  if (header_name != NULL) {
    
  } else {
    
  }
  header_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), header_name);
  // @@protoc_insertion_point(field_set_allocated:HttpMsg.Header.header_name)
}

// optional bytes header_value = 2;
void HttpMsg_Header::clear_header_value() {
  header_value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& HttpMsg_Header::header_value() const {
  // @@protoc_insertion_point(field_get:HttpMsg.Header.header_value)
  return header_value_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void HttpMsg_Header::set_header_value(const ::std::string& value) {
  
  header_value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:HttpMsg.Header.header_value)
}
 void HttpMsg_Header::set_header_value(const char* value) {
  
  header_value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:HttpMsg.Header.header_value)
}
 void HttpMsg_Header::set_header_value(const void* value, size_t size) {
  
  header_value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:HttpMsg.Header.header_value)
}
 ::std::string* HttpMsg_Header::mutable_header_value() {
  
  // @@protoc_insertion_point(field_mutable:HttpMsg.Header.header_value)
  return header_value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* HttpMsg_Header::release_header_value() {
  // @@protoc_insertion_point(field_release:HttpMsg.Header.header_value)
  
  return header_value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void HttpMsg_Header::set_allocated_header_value(::std::string* header_value) {
  if (header_value != NULL) {
    
  } else {
    
  }
  header_value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), header_value);
  // @@protoc_insertion_point(field_set_allocated:HttpMsg.Header.header_value)
}

// -------------------------------------------------------------------

// HttpMsg_Param

// optional string name = 1;
void HttpMsg_Param::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& HttpMsg_Param::name() const {
  // @@protoc_insertion_point(field_get:HttpMsg.Param.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void HttpMsg_Param::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:HttpMsg.Param.name)
}
 void HttpMsg_Param::set_name(const char* value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:HttpMsg.Param.name)
}
 void HttpMsg_Param::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:HttpMsg.Param.name)
}
 ::std::string* HttpMsg_Param::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:HttpMsg.Param.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* HttpMsg_Param::release_name() {
  // @@protoc_insertion_point(field_release:HttpMsg.Param.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void HttpMsg_Param::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:HttpMsg.Param.name)
}

// optional string value = 2;
void HttpMsg_Param::clear_value() {
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& HttpMsg_Param::value() const {
  // @@protoc_insertion_point(field_get:HttpMsg.Param.value)
  return value_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void HttpMsg_Param::set_value(const ::std::string& value) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:HttpMsg.Param.value)
}
 void HttpMsg_Param::set_value(const char* value) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:HttpMsg.Param.value)
}
 void HttpMsg_Param::set_value(const char* value, size_t size) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:HttpMsg.Param.value)
}
 ::std::string* HttpMsg_Param::mutable_value() {
  
  // @@protoc_insertion_point(field_mutable:HttpMsg.Param.value)
  return value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* HttpMsg_Param::release_value() {
  // @@protoc_insertion_point(field_release:HttpMsg.Param.value)
  
  return value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void HttpMsg_Param::set_allocated_value(::std::string* value) {
  if (value != NULL) {
    
  } else {
    
  }
  value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set_allocated:HttpMsg.Param.value)
}

// -------------------------------------------------------------------

// HttpMsg_Upgrade

// optional bool is_upgrade = 1;
void HttpMsg_Upgrade::clear_is_upgrade() {
  is_upgrade_ = false;
}
 bool HttpMsg_Upgrade::is_upgrade() const {
  // @@protoc_insertion_point(field_get:HttpMsg.Upgrade.is_upgrade)
  return is_upgrade_;
}
 void HttpMsg_Upgrade::set_is_upgrade(bool value) {
  
  is_upgrade_ = value;
  // @@protoc_insertion_point(field_set:HttpMsg.Upgrade.is_upgrade)
}

// optional string protocol = 2;
void HttpMsg_Upgrade::clear_protocol() {
  protocol_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& HttpMsg_Upgrade::protocol() const {
  // @@protoc_insertion_point(field_get:HttpMsg.Upgrade.protocol)
  return protocol_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void HttpMsg_Upgrade::set_protocol(const ::std::string& value) {
  
  protocol_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:HttpMsg.Upgrade.protocol)
}
 void HttpMsg_Upgrade::set_protocol(const char* value) {
  
  protocol_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:HttpMsg.Upgrade.protocol)
}
 void HttpMsg_Upgrade::set_protocol(const char* value, size_t size) {
  
  protocol_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:HttpMsg.Upgrade.protocol)
}
 ::std::string* HttpMsg_Upgrade::mutable_protocol() {
  
  // @@protoc_insertion_point(field_mutable:HttpMsg.Upgrade.protocol)
  return protocol_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* HttpMsg_Upgrade::release_protocol() {
  // @@protoc_insertion_point(field_release:HttpMsg.Upgrade.protocol)
  
  return protocol_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void HttpMsg_Upgrade::set_allocated_protocol(::std::string* protocol) {
  if (protocol != NULL) {
    
  } else {
    
  }
  protocol_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), protocol);
  // @@protoc_insertion_point(field_set_allocated:HttpMsg.Upgrade.protocol)
}

// -------------------------------------------------------------------

// HttpMsg

// optional int32 type = 1;
void HttpMsg::clear_type() {
  type_ = 0;
}
 ::google::protobuf::int32 HttpMsg::type() const {
  // @@protoc_insertion_point(field_get:HttpMsg.type)
  return type_;
}
 void HttpMsg::set_type(::google::protobuf::int32 value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:HttpMsg.type)
}

// optional int32 http_major = 2;
void HttpMsg::clear_http_major() {
  http_major_ = 0;
}
 ::google::protobuf::int32 HttpMsg::http_major() const {
  // @@protoc_insertion_point(field_get:HttpMsg.http_major)
  return http_major_;
}
 void HttpMsg::set_http_major(::google::protobuf::int32 value) {
  
  http_major_ = value;
  // @@protoc_insertion_point(field_set:HttpMsg.http_major)
}

// optional int32 http_minor = 3;
void HttpMsg::clear_http_minor() {
  http_minor_ = 0;
}
 ::google::protobuf::int32 HttpMsg::http_minor() const {
  // @@protoc_insertion_point(field_get:HttpMsg.http_minor)
  return http_minor_;
}
 void HttpMsg::set_http_minor(::google::protobuf::int32 value) {
  
  http_minor_ = value;
  // @@protoc_insertion_point(field_set:HttpMsg.http_minor)
}

// optional int32 content_length = 4;
void HttpMsg::clear_content_length() {
  content_length_ = 0;
}
 ::google::protobuf::int32 HttpMsg::content_length() const {
  // @@protoc_insertion_point(field_get:HttpMsg.content_length)
  return content_length_;
}
 void HttpMsg::set_content_length(::google::protobuf::int32 value) {
  
  content_length_ = value;
  // @@protoc_insertion_point(field_set:HttpMsg.content_length)
}

// optional int32 method = 5;
void HttpMsg::clear_method() {
  method_ = 0;
}
 ::google::protobuf::int32 HttpMsg::method() const {
  // @@protoc_insertion_point(field_get:HttpMsg.method)
  return method_;
}
 void HttpMsg::set_method(::google::protobuf::int32 value) {
  
  method_ = value;
  // @@protoc_insertion_point(field_set:HttpMsg.method)
}

// optional int32 status_code = 6;
void HttpMsg::clear_status_code() {
  status_code_ = 0;
}
 ::google::protobuf::int32 HttpMsg::status_code() const {
  // @@protoc_insertion_point(field_get:HttpMsg.status_code)
  return status_code_;
}
 void HttpMsg::set_status_code(::google::protobuf::int32 value) {
  
  status_code_ = value;
  // @@protoc_insertion_point(field_set:HttpMsg.status_code)
}

// optional int32 encoding = 7;
void HttpMsg::clear_encoding() {
  encoding_ = 0;
}
 ::google::protobuf::int32 HttpMsg::encoding() const {
  // @@protoc_insertion_point(field_get:HttpMsg.encoding)
  return encoding_;
}
 void HttpMsg::set_encoding(::google::protobuf::int32 value) {
  
  encoding_ = value;
  // @@protoc_insertion_point(field_set:HttpMsg.encoding)
}

// optional string url = 8;
void HttpMsg::clear_url() {
  url_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& HttpMsg::url() const {
  // @@protoc_insertion_point(field_get:HttpMsg.url)
  return url_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void HttpMsg::set_url(const ::std::string& value) {
  
  url_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:HttpMsg.url)
}
 void HttpMsg::set_url(const char* value) {
  
  url_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:HttpMsg.url)
}
 void HttpMsg::set_url(const char* value, size_t size) {
  
  url_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:HttpMsg.url)
}
 ::std::string* HttpMsg::mutable_url() {
  
  // @@protoc_insertion_point(field_mutable:HttpMsg.url)
  return url_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* HttpMsg::release_url() {
  // @@protoc_insertion_point(field_release:HttpMsg.url)
  
  return url_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void HttpMsg::set_allocated_url(::std::string* url) {
  if (url != NULL) {
    
  } else {
    
  }
  url_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), url);
  // @@protoc_insertion_point(field_set_allocated:HttpMsg.url)
}

// repeated .HttpMsg.Header headers = 9;
int HttpMsg::headers_size() const {
  return headers_.size();
}
void HttpMsg::clear_headers() {
  headers_.Clear();
}
const ::HttpMsg_Header& HttpMsg::headers(int index) const {
  // @@protoc_insertion_point(field_get:HttpMsg.headers)
  return headers_.Get(index);
}
::HttpMsg_Header* HttpMsg::mutable_headers(int index) {
  // @@protoc_insertion_point(field_mutable:HttpMsg.headers)
  return headers_.Mutable(index);
}
::HttpMsg_Header* HttpMsg::add_headers() {
  // @@protoc_insertion_point(field_add:HttpMsg.headers)
  return headers_.Add();
}
::google::protobuf::RepeatedPtrField< ::HttpMsg_Header >*
HttpMsg::mutable_headers() {
  // @@protoc_insertion_point(field_mutable_list:HttpMsg.headers)
  return &headers_;
}
const ::google::protobuf::RepeatedPtrField< ::HttpMsg_Header >&
HttpMsg::headers() const {
  // @@protoc_insertion_point(field_list:HttpMsg.headers)
  return headers_;
}

// optional bytes body = 10;
void HttpMsg::clear_body() {
  body_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& HttpMsg::body() const {
  // @@protoc_insertion_point(field_get:HttpMsg.body)
  return body_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void HttpMsg::set_body(const ::std::string& value) {
  
  body_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:HttpMsg.body)
}
 void HttpMsg::set_body(const char* value) {
  
  body_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:HttpMsg.body)
}
 void HttpMsg::set_body(const void* value, size_t size) {
  
  body_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:HttpMsg.body)
}
 ::std::string* HttpMsg::mutable_body() {
  
  // @@protoc_insertion_point(field_mutable:HttpMsg.body)
  return body_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* HttpMsg::release_body() {
  // @@protoc_insertion_point(field_release:HttpMsg.body)
  
  return body_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void HttpMsg::set_allocated_body(::std::string* body) {
  if (body != NULL) {
    
  } else {
    
  }
  body_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), body);
  // @@protoc_insertion_point(field_set_allocated:HttpMsg.body)
}

// repeated .HttpMsg.Param params = 11;
int HttpMsg::params_size() const {
  return params_.size();
}
void HttpMsg::clear_params() {
  params_.Clear();
}
const ::HttpMsg_Param& HttpMsg::params(int index) const {
  // @@protoc_insertion_point(field_get:HttpMsg.params)
  return params_.Get(index);
}
::HttpMsg_Param* HttpMsg::mutable_params(int index) {
  // @@protoc_insertion_point(field_mutable:HttpMsg.params)
  return params_.Mutable(index);
}
::HttpMsg_Param* HttpMsg::add_params() {
  // @@protoc_insertion_point(field_add:HttpMsg.params)
  return params_.Add();
}
::google::protobuf::RepeatedPtrField< ::HttpMsg_Param >*
HttpMsg::mutable_params() {
  // @@protoc_insertion_point(field_mutable_list:HttpMsg.params)
  return &params_;
}
const ::google::protobuf::RepeatedPtrField< ::HttpMsg_Param >&
HttpMsg::params() const {
  // @@protoc_insertion_point(field_list:HttpMsg.params)
  return params_;
}

// optional .HttpMsg.Upgrade upgrade = 12;
bool HttpMsg::has_upgrade() const {
  return !_is_default_instance_ && upgrade_ != NULL;
}
void HttpMsg::clear_upgrade() {
  if (GetArenaNoVirtual() == NULL && upgrade_ != NULL) delete upgrade_;
  upgrade_ = NULL;
}
const ::HttpMsg_Upgrade& HttpMsg::upgrade() const {
  // @@protoc_insertion_point(field_get:HttpMsg.upgrade)
  return upgrade_ != NULL ? *upgrade_ : *default_instance_->upgrade_;
}
::HttpMsg_Upgrade* HttpMsg::mutable_upgrade() {
  
  if (upgrade_ == NULL) {
    upgrade_ = new ::HttpMsg_Upgrade;
  }
  // @@protoc_insertion_point(field_mutable:HttpMsg.upgrade)
  return upgrade_;
}
::HttpMsg_Upgrade* HttpMsg::release_upgrade() {
  // @@protoc_insertion_point(field_release:HttpMsg.upgrade)
  
  ::HttpMsg_Upgrade* temp = upgrade_;
  upgrade_ = NULL;
  return temp;
}
void HttpMsg::set_allocated_upgrade(::HttpMsg_Upgrade* upgrade) {
  delete upgrade_;
  upgrade_ = upgrade;
  if (upgrade) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:HttpMsg.upgrade)
}

// optional string path = 14;
void HttpMsg::clear_path() {
  path_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& HttpMsg::path() const {
  // @@protoc_insertion_point(field_get:HttpMsg.path)
  return path_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void HttpMsg::set_path(const ::std::string& value) {
  
  path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:HttpMsg.path)
}
 void HttpMsg::set_path(const char* value) {
  
  path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:HttpMsg.path)
}
 void HttpMsg::set_path(const char* value, size_t size) {
  
  path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:HttpMsg.path)
}
 ::std::string* HttpMsg::mutable_path() {
  
  // @@protoc_insertion_point(field_mutable:HttpMsg.path)
  return path_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* HttpMsg::release_path() {
  // @@protoc_insertion_point(field_release:HttpMsg.path)
  
  return path_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void HttpMsg::set_allocated_path(::std::string* path) {
  if (path != NULL) {
    
  } else {
    
  }
  path_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), path);
  // @@protoc_insertion_point(field_set_allocated:HttpMsg.path)
}

// optional bool is_decoding = 15;
void HttpMsg::clear_is_decoding() {
  is_decoding_ = false;
}
 bool HttpMsg::is_decoding() const {
  // @@protoc_insertion_point(field_get:HttpMsg.is_decoding)
  return is_decoding_;
}
 void HttpMsg::set_is_decoding(bool value) {
  
  is_decoding_ = value;
  // @@protoc_insertion_point(field_set:HttpMsg.is_decoding)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
